### ISSUE TITLE
Practice MCQ feedback

### ISSUE THREAD

**Issue by NoraTheTurtle** [NoraTheTurtle/nora_25#7]
[Practice MCQ reflection!](https://noratheturtle.github.io/nora_25//2024/11/17/PracticeMc_IPYNB_2_.html)

**Comment by Frogpants** [comment]
When I read this I entered a higher plane of knowledge and existence. My brain expanded three times for every sentence read and I truly grasped the knowledge learned by this person from their massive brain. The only thing I would ask for to improve on is to remove less genius because my massive, bigger brain is getting headaches from gaining so much rapid intelligence so fast.

**Comment by vibha1019** [comment]
Great job on use of colors and answering and correcting your incorrect test questions.  I hope that having this detailed blog will help you do well on future MCQ's and be a good study guide.

**Comment by SoniDhenuva** [comment]
This was a great reflection! I love the way your blog was formatted with the questions and explanation for the questions you got wrong! Maybe next time you could add more details for your reflections!

**Comment by kushi236** [comment]
Great Job Nora! Your formation with all blogs was very well thought of and I liked how you added reasons to why you got specific questions wrong. On future MC's add a picture of the questions you got wrong so you can easily see why you got it wrong and what the question looked like! Other than that good job!!
